[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://github.com/henryjhu/Country-Resolution-LLM-and-GeoNames-Database/blob/main/LLM%20Data%20Preparation.ipynb)

<Strong> <font face="Verdana" size="5"> AML Country Resolution Via LLM and GeoNames Database Search </font></strong> <br>
<b> <font face="Verdana" size="3"> Project Highlight: </font></b><br>
<font face="Verdana" size="3"> This is the exact replica of the work which was carried out on a real project at one of the banks. </font><br>
<b> <font face="Verdana" size="3"> Project Objective: </font></b><br>
<font face="Verdana" size="3"> Unstructured ISO 20022 SWIFT pacs.008 messages contain free-form address fields that may include typographical errors, incomplete address information, and missing country names for both originators and beneficiaries. These data quality issues make it challenging for banks to accurately identify the countries associated with cross-border wire transfers, potentially affecting Anti-Money Laundering (AML) compliance monitoring. The objective of this project is to leverage both Large Language Model (LLM) and GeoNames Database Searches for correctly identifying the countries of these very messy address texts. Accurate country resolution helps transaction monitoring rules and sanction screen rules correctly identify cross-border transactions. </font><br>
<b> <font face="Verdana" size="3">Data Scientist:</font></b><font face="Verdana" size="3"> Henry J. Hu</font><br>
<b> <font face="Verdana" size="3">Runtime and Inference Engine:</font></b><font face="Verdana" size="3"> Ollama</font><br>
<b> <font face="Verdana" size="3">Programming Language:</font></b><font face="Verdana" size="3"> Python</font><br>
<b> <font face="Verdana" size="3"> Data Source: </font></b><br>
<font face="Verdana" size="3"> Data Owner: </font> <a href="https://postalcodezip.com ">postalcodezip.com</a> <br>
<font face="Verdana" size="3"> Number of Countries: </font> 25 <br>
<font face="Verdana" size="3"> Number of Addresses: </font> 2290 <br>
<b> <font face="Verdana" size="3"> Data Privacy: </font></b><br>
<font face="Verdana" size="3">
Because company policy requires all employees to sign a Non-Disclosure Agreement (NDA) that prohibits the disclosure of confidential information related to the company’s data and business operations, this replica machine learning project uses only freely and publicly accessible data. The project does not disclose or contain any confidential information related to any company’s data, operations, or business practices.
</font><br>
<b> <font face="Verdana" size="3">Last Update:</font></b><font face="Verdana" size="3"> October 21st, 2026</font>

# Importing Libraries

In [126]:
import os
import sys
import pandas as pd
import numpy as np
import ollama
import json
import requests
import time
import subprocess
from google.colab import drive

# Setting Up Ollama Runtime Environment and Inference Engine

In [128]:
# This is a Llama API key acts as a digital ID, secret token or password used for authenticating the code or application when sending requests to run Meta's open-source Llama artificial intelligence models.
os.environ["OLLAMA_KEEP_ALIVE"]= '0'
os.environ['OLLAMA_FLASH_ATTENTION'] = '1'
os.environ['OLLAMA_KV_CACHE_TYPE'] = 'q8_0'  # Optional: Greatly reduces VRAM usage alongside Flash Attention
os.environ['OLLAMA_MAX_LOADED_MODELS'] = '1'

In [129]:
# Increase the maximum height and width of the output area.
os.system("mode con cols=50 lines=5000")

32512

In [130]:
# Set the column width to unlimited
pd.set_option('display.max_colwidth', None)

In [131]:
!apt update

Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble InRelease
Get:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:5 https://r2u.stat.illinois.edu/ubuntu noble InRelease [9,161 B]
Hit:6 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:7 https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/ InRelease
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble InRelease [17.8 kB]
Hit:9 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu noble InRelease
Get:11 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [2,172 kB]
Get:12 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1,733 kB]
Fetched 4,058 kB in 3s (1,195 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
50 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)

In [132]:
!apt install lspci

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package lspci

In [133]:
!apt install -y pciutils

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pciutils is already the newest version (1:3.10.0-2build1).
0 upgraded, 0 newly installed, 0 to remove and 50 not upgraded.

In [134]:
!apt install zstd

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
zstd is already the newest version (1.5.5+dfsg2-2build1.1).
0 upgraded, 0 newly installed, 0 to remove and 50 not upgraded.

In [135]:
# Installing Ollama
print("Installing Ollama...")
subprocess.run("curl -fsSL https://ollama.com/install.sh | sh", shell=True)

Installing Ollama...

CompletedProcess(args='curl -fsSL https://ollama.com/install.sh | sh', returncode=0)

In [136]:
# Start the ollama server as a background process
os.makedirs("/content/ollama_logs", exist_ok = True)
log = open("/content/ollama_logs/server.log","w")
proc=subprocess.Popen(
	["ollama", "serve"],
	stdout=log, stderr=log,
	env={**os.environ, "OLLAMA_HOST": "0.0.0.0:11434"}
)

# Wait until the server responds is up runnng
for i in range(30):
  try:
    r=requests.get("http://localhost:11434/api/tags", timeout=1)
    if r.ok:
      print("Ollama server is up!")
      break
  except Exception:
    pass
  time.sleep(5)
else:
  print("Ollama did not start in time")

Ollama server is up!

In [137]:
# Installing llama3.1:8b
print("Installing llama3.1:8b...")
subprocess.run("ollama run llama3.1:8b", shell=True)

Installing llama3.1:8b...

CompletedProcess(args='ollama run llama3.1:8b', returncode=0)

In [138]:
!ollama list

NAME           ID              SIZE      MODIFIED
llama3.1:8b    46e0c10c039e    4.9 GB    3 hours ago

In [39]:
!pip install -q ollama

In [58]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

# Mounting Google Drive

In [42]:
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

# Importing Data

In [158]:
df = pd.read_excel("gdrive/MyDrive/Github_Projects/LLM_Addresses.xlsx", index_col = None)

# Exploratory Data Analysis

In [141]:
# Find out the number of rows and columns on the dataframe
df.shape

(200, 13)

In [142]:
# Find out the data type of each column on the dataframe
df.dtypes

index                   int64
MessageType            object
CountryCodeVerified    object
Address                object
Number                 object
Street                 object
Region                 object
City                   object
State                  object
Province               object
PostalCode             object
CountryCodeLLM         object
ConfidenceScore        object
dtype: object

In [143]:
# Find out the number of null values in each column on the dataframe
df.isnull().sum()

index                    0
MessageType              0
CountryCodeVerified      0
Address                  0
Number                  89
Street                  77
Region                  66
City                    76
State                  137
Province               152
PostalCode              97
CountryCodeLLM          77
ConfidenceScore         71
dtype: int64

In [144]:
# Examine the first 5 rows of the dataframe
df.head(n=5)

,index,MessageType,CountryCodeVerified,Address,Number,Street,Region,City,State,Province,PostalCode,CountryCodeLLM,ConfidenceScore
0,2178,pacs.008,GB,"Moor Lane, England, Willoughby , , , CV23 8BT",CV23 8BT,Moor Lane,England,Willoughby,NaN,NaN,CV23 8BT,GB,Our analysis suggests that the provided address is a UK address.
1,1271,pacs.008,NG,"Tolupe St. Ikeja Lagos State , 100263",100263,Tolupe St.,Ikeja,Lagos,Lagos State,NaN,100263,NG,0.9
2,1268,pacs.008,NG,"Omolola St., , Lagos Lagos State, , 101213",NaN,Omolola St.,Lagos,Lagos,Lagos State,NaN,101213,NG,class 2
3,44,pacs.008,AR,"Calle Bolivia, Buenos Aires Moreno B1744 CFI",Calle Bolivia,Bolivia,Buenos Aires,Moreno,NaN,NaN,B1744,CFI,?
4,2025,pacs.008,AE,"شارع 8, أبوظبي العين, , , 30055",8,شارع 8,أبوظبي,العين,NaN,NaN,30055,AE,default

In [145]:
# Retrieve the last 5 rows of the dataframe
df.tail(n=5)

,index,MessageType,CountryCodeVerified,Address,Number,Street,Region,City,State,Province,PostalCode,CountryCodeLLM,ConfidenceScore
195,332,pacs.008,CL,"General Salvo, Región Metropolitana de Santiago, Providencia, , , 7500713",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,1290,pacs.008,NG,"Uden St. , Awka, Anambra State, , , 420231",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,69,pacs.008,AR,"Calle Lumiere, Córdoba Cordoba , X5020 FCB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,530,pacs.008,GE,"შ 109 Imereti Sochkheti, ,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,1380,pacs.008,RU,"Stroitelnaya ul, Hakasiya Resp, Fyrkal s, , , 655232",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Phase 1: Extract Address Components
<b> <font face="Verdana" size="3"> Objective: </font></b><br>
The first objective is to take advantage of Llama's ability to infer from the address components in the text for determinting the country.<br>
The second objective is to take advantage of Llama's ability to extract address components from very messy international addresses.

<b> <font face="Verdana" size="3"> Model Information: </font></b><br>
<font face="Verdana" size="3"> Model Developer:</font> Meta<br>
<font face="Verdana" size="3"> Model Version:</font> llama3.1:8b<br>
<font face="Verdana" size="3">Model Page:</font>
https://huggingface.co/meta-llama/Llama-3.1-8B
<br>
<font face="Verdana" size="3">Model Description:</font>
The Meta Llama 3.1 collection of multilingual large language models (LLMs) is a collection of pretrained and instruction tuned generative models in 8B, 70B and 405B sizes (text in/text out). The Llama 3.1 instruction tuned text only models (8B, 70B, 405B) are optimized for multilingual dialogue use cases and outperform many of the available open source and closed chat models on common industry benchmarks.

In [113]:
##############################################################################################
# Purpose:
# This function is used for extracting individual address components from a text string.
##############################################################################################

def AddressParser (df):
    # Define the JSON schema for the address components
    schema = {
        "type": "object",
        "properties": {
            "Number": {"type": "string"},
            "Street": {"type": "string"},
            "Region": {"type": "string"},
            "City": {"type": "string"},
            "State": {"type": "string"},
            "Province": {"type": "string"},
            "District": {"type": "string"},
            "Postal Code": {"type": "string"},
            "Inferred Country ISO2 Code":  {"type": "string"},
            "Confidence Score" :   {"type": "string"},
        },
        "required": ['Number', 'Street', 'Region', 'City', 'State', 'Province', 'District', 'Postal Code','Inferred Country ISO2 Code','Confidence Score'],
    }

    # Record the process start time
    start_time = time.perf_counter()

    for row in df.itertuples(index=True):
        # Access attributes using dot notation (.Column_Name)
        print(f"Index: {row.Index}, Address: {row.Address}")

        inputTxt = row.Address
        replacements = {"'": " ",'"': " ","\n": " ","\\n": " ","\t": " ","\\": " "}
        for old, new in replacements.items():
            inputTxt = inputTxt.replace(old, new)

        #inputTxt = "Aden - Mukalla Raod# Abyan Governorate@ حورة: . . : "
        prompt = "Parse this address:" + inputTxt
        try:
            response = requests.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": "llama3.1:8b",
                    "prompt": prompt,
                    "format": schema,  # Enforces structured JSON output
                    "stream": False,
                    "keep_alive": 0,
                },
            )
            parsed_address = json.loads(response.json()["response"])
            print(json.dumps(parsed_address, indent=2))

            # put the extracted address components back into the orginal dataframe
            df.at[row.Index,'Number' ] = parsed_address['Number']
            df.at[row.Index,'Street' ] = parsed_address['Street']
            df.at[row.Index,'Region' ] = parsed_address['Region']
            df.at[row.Index,'City' ] = parsed_address['City']
            df.at[row.Index,'State' ] = parsed_address['State']
            df.at[row.Index,'Province' ] = parsed_address['Province']
            df.at[row.Index,'PostalCode' ] = parsed_address['Postal Code']
            df.at[row.Index,'CountryCodeLLM' ] = parsed_address['Inferred Country ISO2 Code']
            df.at[row.Index,'ConfidenceScore' ] = parsed_address['Confidence Score']

        except json.JSONDecodeError as e:
            print(f"JSONDecodeError: {e}")
            pass
        except ValueError as e:
            print(f"ValueError: {e}")
            pass
        except ollama.ResponseError as e:
            # Handles API or server-side errors from Ollama
            print(f"Ollama API Error: {e.error} (Status code: {e.status_code})")
            pass
        except ConnectionError as e:
            print(f"ConnectionError: {e}")
            pass
        except Exception as e:
            # Catches any unexpected general errors
            print(f"Other Exception: {e}")
            pass

    # Record the process end time
    end_time = time.perf_counter()
    # Calculate process elapsed time
    execution_time = end_time - start_time
    print(f"Execution time: {execution_time:.6f} seconds")

In [159]:
# Get a random sample of addresses for testing.
np.random.seed(42)
df1 = df.sample(n=200)
df1 = df1.reset_index()

In [160]:
df1.shape

(77, 13)

In [162]:
AddressParser (df1)

Index: 7, Address:  151 Street  Sharjah, Sharjah,     ,
{
  "Number": "151",
  "Street": "Street",
  "Region": "Sharjah",
  "City": "Sharjah",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "AE",
  "Confidence Score": "Some"
}
Index: 24, Address:  Caserio el Rebellon, Principado de Asturias, Godella,       33758
{
  "Number": "33758",
  "Street": "Caserio el Rebellon",
  "Region": "Principado de Asturias",
  "City": "Godella",
  "State": "Asturias",
  "Province": "Asturias",
  "District": "Unknown",
  "Postal Code": "33758",
  "Inferred Country ISO2 Code": "ES",
  "Confidence Score": "1"
}
Index: 26, Address:  طريق الجبجب الثلوث, Dhamar Governorate, Al Hudayyah,
{
  "Number": "",
  "Street": "\u0627\u0644\u062c\u0628\u062c\u0628 \u0627\u0644\u062b\u0644\u0648\u062b",
  "Region": "Dhamar Governorate",
  "City": "Al Hudayyah",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "YE",
  "Confidence Score": "For more information visit: https://nominatim.openstreetmap.org/search?q=\u0627\u0644\u062c\u0628\u062c\u0628%20\u0627\u0644\u062b\u0644\u0648\u062b%20Dhamar%20Governorate%20Al%20Hudayyah&format=json&limit=1"
}
Index: 45, Address:  Calle Bosc, Cataluña, Rubí  ,   , 8191
{
  "Number": ",",
  "Street": "Calle Bosc",
  "Region": "Catalu\u00f1a",
  "City": "Rub\u00ed",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "8191",
  "Inferred Country ISO2 Code": "ES",
  "Confidence Score": "catalonia is not a city, but a region, and Rubi is a city in the region."
}
Index: 56, Address:  Nitsanim  Haifa  Haifa  ,   , 34354 37
{
  "Number": ": 34354",
  "Street": "Nitsanim",
  "Region": "Haifa",
  "City": "Haifa",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "34354",
  "Inferred Country ISO2 Code": "IL",
  "Confidence Score": ": 0.2"
}
Index: 70, Address:  Пограничная полоса Border Line  Grodno Region  Сопоцкинский сельский Совет, , ,
{
  "Number": "\u041f\u043e\u0433\u0440\u0430\u043d\u0438\u0447\u043d\u0430\u044f \u043f\u043e\u043b\u043e\u0441\u0430",
  "Street": "Border Line",
  "Region": "Grodno Region",
  "City": "\u0421\u043e\u043f\u043e\u0446\u043a\u0438\u043d\u0441\u043a\u0438\u0439 \u0441\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u0421\u043e\u0432\u0435\u0442",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "BY",
  "Confidence Score": "0.8"
}
Index: 75, Address:  Carretera Central  Guantánamo, Baitiqurí, , ,
{
  "Number": "Carretera Central",
  "Street": "Carretera Central",
  "Region": "Guant\u00e1namo",
  "City": "Baitiqur\u00ed",
  "State": "Guant\u00e1namo",
  "Province": "Guant\u00e1namo",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "CU",
  "Confidence Score": "Medium"
}
Index: 81, Address:  Diseminado Afores  Cataluña, Pegueroles  , ,   25286
{
  "Number": "25286",
  "Street": "Diseminado Afores",
  "Region": "Catalu\u00f1a",
  "City": "Pegueroles",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "25286",
  "Inferred Country ISO2 Code": "ES",
  "Confidence Score": "Implicit"
}
Index: 84, Address:  Carretera Sancti Spiritus - Yaguajay  Sancti Spiritus, Jíquima de Peláez    , ,
{
  "Number": "",
  "Street": "Carretera Sancti Spiritus - Yaguajay",
  "Region": "Sancti Spiritus",
  "City": "J\u00edquima de Pel\u00e1ez",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "",
  "Confidence Score": "}"
}
Index: 93, Address:  ზუგდიდი-ჯვარი-მესტია-ლასდილი, Samegrelo-Upper Svaneti  Zeda Etseri, , , ,
{
  "Number": "} ZUGDIDI-\u10ef\u10d5\u10d0\u10e0\u10d8-\u10db\u10d4\u10e1\u10e2\u10d8\u10d0-\u10da\u10d0\u10e1\u10d3\u10d8\u10da\u10d8, Samegrelo-Upper Svaneti",
  "Street": "Zeda Etseri",
  "Region": "",
  "City": "Zugdidi",
  "State": "Samegrelo-Upper Svaneti",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "",
  "Confidence Score": "}"
}
Index: 113, Address:  شارع محمد بن مطر  الفجيرة, الفجيرة  ,
{
  "Number": "",
  "Street": "\u0627\u0644\u0642\u0627\u062f\u062d \u0627\u0644\u0625\u062b\u0646 \u0627\u0644\u0627\u0644\u0627\u0643\u0627\u0644\u064a",
  "Region": "\u0641\u062c\u064a\u0631\u0629",
  "City": "\u0641\u062c\u064a\u0631\u0629",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "",
  "Confidence Score": "Not Given"
}
Index: 134, Address:  Бывшая УЖД "Большие Чучевичи - Гоцк"  Minsk Region  Копацевичский сельский Совет, ,
{
  "Number": "\u0411\u044b\u0432\u0448\u0430\u044f \u0423\u0416\u0414",
  "Street": "\u0411\u043e\u043b\u044c\u0448\u0438\u0435 \u0427\u0443\u0447\u0435\u0432\u0438\u0447\u0438",
  "Region": "Minsk Region",
  "City": "\u0413\u043e\u0446\u043a",
  "State": "None",
  "Province": "\u041a\u043e\u043f\u0430\u0446\u0435\u0432\u0438\u0447\u0441\u043a\u0438\u0439 \u0441\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u0421\u043e\u0432\u0435\u0442",
  "District": "None",
  "Postal Code": "None",
  "Inferred Country ISO2 Code": "None",
  "Confidence Score": "x"
}
Index: 135, Address:  Main Street,   Dewanagala    Sabaragamuwa  Kegalle, 71527
{
  "Number": "71527",
  "Street": "Main Street",
  "Region": "Sabaragamuwa",
  "City": "Dewanagala",
  "State": "Kegalle",
  "Province": "Sabaragamuwa",
  "District": "Kegalle",
  "Postal Code": "71527",
  "Inferred Country ISO2 Code": "LK",
  "Confidence Score": "0.7"
}
Index: 136, Address:  Carretera Cifuentes - Calabazar de Sagua  Villa Clara  Calabazar de Sagua, ,   ,
{
  "Number": "",
  "Street": "Carretera",
  "Region": "Cifuentes - Calabazar de Sagua",
  "City": "Villa Clara",
  "State": "",
  "Province": "",
  "District": "Calabazar de Sagua",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "CU",
  "Confidence Score": "name: 0.995, state: 0.005, province: 0.005, district: 0.995"
}
Index: 137, Address:  Dhahar Highway, Sanaag, Dhahar    , ,
{
  "Number": "",
  "Street": "Dhahar Highway",
  "Region": "Sanaag",
  "City": "Dhahar",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "",
  "Confidence Score": "} }  "
}
Index: 138, Address:  улица Гуляева  Minsk Region  Starobin    , , 223730
{
  "Number": "223730",
  "Street": "\u0443\u043b\u0438\u0446\u0430 \u0413\u0443\u043b\u044f\u0435\u0432\u0430",
  "Region": "Minsk Region",
  "City": "Starobin",
  "State": "Belarus",
  "Province": "",
  "District": "",
  "Postal Code": "223730",
  "Inferred Country ISO2 Code": "BY",
  "Confidence Score": "0.99"
}
Index: 139, Address:  Babanle St.    Abeokuta, Ogun State      110213
{
  "Number": "Babanle St.",
  "Street": "Babanle St.",
  "Region": "Abeokuta",
  "City": "Abeokuta",
  "State": "Ogun State",
  "Province": "Ogun State",
  "District": "",
  "Postal Code": "110213",
  "Inferred Country ISO2 Code": "NG",
  "Confidence Score": "0.9"
}
Index: 140, Address:  Omalo-Jvarboseli  Kakheti, Bochorna      ,
{
  "Number": "Not Available",
  "Street": "Omalo-Jvarboseli",
  "Region": "Kakheti",
  "City": "Bochorna",
  "State": "Not Available",
  "Province": "Not Available",
  "District": "Not Available",
  "Postal Code": "Not Available",
  "Inferred Country ISO2 Code": "GE",
  "Confidence Score": "High"
}
Index: 141, Address:  Carretera Cayo Mambí - Sagua, Holguín  Cayo Mambí, ,     83200
{
  "Number": "83200",
  "Street": "Carretera",
  "Region": "Sagua",
  "City": "Holgu\u00edn",
  "State": "Cayo Mamb\u00ed",
  "Province": "Unknown",
  "District": "Unknown",
  "Postal Code": "83200",
  "Inferred Country ISO2 Code": "CU",
  "Confidence Score": "Some"
}
Index: 142, Address:  Rua Durval Batista Oliveira, Minas Gerais, Paracatu    ,   38600-000
{
  "Number": "38600-000",
  "Street": "Rua Durval Batista Oliveira",
  "Region": "Paracatu",
  "City": "Minas Gerais",
  "State": "Minas Gerais",
  "Province": "Minas Gerais",
  "District": "Minas Gerais",
  "Postal Code": "38600-000",
  "Inferred Country ISO2 Code": "BR",
  "Confidence Score": "0.91"
}
Index: 143, Address:  Amir abad, Qazvin Province  Babin,   ,
{
  "Number": "Babin",
  "Street": "Amir Abad",
  "Region": "Qazvin Province",
  "City": "Qazvin",
  "State": "Iran",
  "Province": "Qazvin Province",
  "District": "Qazvin",
  "Postal Code": "Unknown",
  "Inferred Country ISO2 Code": "IR",
  "Confidence Score": "0.85"
}
Index: 144, Address:  21  Ilam Province, چم بور فرخینوند,   , ,
{
  "Number": "21",
  "Street": "Ilam Province",
  "Region": "Cham Bor",
  "City": "Feraghanin",
  "State": "Ilam",
  "Province": "Ilam Province",
  "District": "Ilam Province",
  "Postal Code": "Not Provided",
  "Inferred Country ISO2 Code": "IR",
  "Confidence Score": "title: ilam | region: ilam | city: feraghanin | address format: iranian | "
}
Index: 145, Address:  Calle 3001, Northern  Nazareth,       1603682
{
  "Number": "3001",
  "Street": "Calle",
  "Region": "Northern",
  "City": "Nazareth",
  "State": "Not specified",
  "Province": "Not specified",
  "District": "Not specified",
  "Postal Code": "1603682",
  "Inferred Country ISO2 Code": "IL",
  "Confidence Score": "0.83"
}
Index: 146, Address:  Osibogun St.    Ijebu Ode, Ogun State,   , 120241
{
  "Number": "Osibogun St.",
  "Street": "",
  "Region": "Ijebu Ode",
  "City": "",
  "State": "Ogun State",
  "Province": "",
  "District": "",
  "Postal Code": "120241",
  "Inferred Country ISO2 Code": "NG",
  "Confidence Score": "These address components have been identified: Street Name: Osibogun St. Region: Ijebu Ode, City: (no city specified), State: Ogun State, Postal Code: 120241. Note: The country has not been explicitly specified, but based on the postal code, it is inferred to be Nigeria. "
}
Index: 147, Address:  Binnie Street, Northland  Paihia,       200
{
  "Number": "200",
  "Street": "Binnie Street",
  "Region": "Northland",
  "City": "Paihia",
  "State": "Not Applicable",
  "Province": "Northland",
  "District": "Far North District",
  "Postal Code": "025-029",
  "Inferred Country ISO2 Code": "NZ",
  "Confidence Score": "If address is valid this score will be above 90"
}
Index: 148, Address:  Rassvetnyy per  Krasnodarskiy kray  Tbilisskaya st-ca  , ,   352363
{
  "Number": "Rassvetnyy per",
  "Street": "Rassvetnyy per",
  "Region": "Krasnodarskiy kray",
  "City": "Tbilisskaya",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "352363",
  "Inferred Country ISO2 Code": "",
  "Confidence Score": "}"
}
Index: 149, Address:  Calle Coronel Charlone  Buenos Aires, San Miguel, ,     B1663 NVU
{
  "Number": "Calle Coronel Charlone",
  "Street": "Calle",
  "Region": "Buenos Aires",
  "City": "San Miguel",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "B1663",
  "Inferred Country ISO2 Code": "AR",
  "Confidence Score": "High"
}
Index: 150, Address:  Avtalyon, Central  El'ad  , , , 4080635
{
  "Number": "4080635",
  "Street": "Avtalyon",
  "Region": "Central El ad ",
  "City": "",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "4080635",
  "Inferred Country ISO2 Code": "IL",
  "Confidence Score": "title="
}
Index: 151, Address:  Main Street  , Leemagahakotuwa  , Central  Kandy  20482
{
  "Number": "20482",
  "Street": "Main Street",
  "Region": "Central",
  "City": "Kandy",
  "State": "Leemagahakotuwa",
  "Province": " ",
  "District": "Kandy",
  "Postal Code": "20482",
  "Inferred Country ISO2 Code": "LK",
  "Confidence Score": "}  "
}
Index: 152, Address:  Söderskogen, Uppsala, Österbybruk,     , 748 93
{
  "Number": "748 93",
  "Street": "S\u00f6derskogen",
  "Region": "Uppsala",
  "City": "\u00d6sterbybruk",
  "State": "None",
  "Province": "None",
  "District": "None",
  "Postal Code": "748 93",
  "Inferred Country ISO2 Code": "None",
  "Confidence Score": "High"
}
Index: 153, Address:  Chalus Road, Mazandaran Province, Seyedkhanesar  , ,
{
  "Number": "Chalus Road",
  "Street": "",
  "Region": "Mazandaran Province",
  "City": "Seyedkhanesar",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "IR",
  "Confidence Score": "0"
}
Index: 154, Address:  Tudor Avenue, Hawke's Bay, Hastings  , ,   4122
{
  "Number": "",
  "Street": "Tudor Avenue",
  "Region": "Hawke's Bay",
  "City": "Hastings",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "4122",
  "Inferred Country ISO2 Code": "NZ",
  "Confidence Score": "Our confidence in the accuracy of the address is very high."
}
Index: 155, Address:  101B Street  Ras Al Khaimah  Ras Al Khaimah,       72324
{
  "Number": "101B",
  "Street": "Street",
  "Region": "Ras Al Khaimah",
  "City": "Ras Al Khaimah",
  "State": "Ras Al Khaimah",
  "Province": "Ras Al Khaimah",
  "District": "Ras Al Khaimah",
  "Postal Code": "72324",
  "Inferred Country ISO2 Code": "AE",
  "Confidence Score": "High"
}
Index: 156, Address:  Rutån  Dalarna  Vansbro,   ,   786 91
{
  "Number": "/786 91",
  "Street": "Rut\u00e5n",
  "Region": "Dalarna",
  "City": "Vansbro",
  "State": "Sweden",
  "Province": "",
  "District": "",
  "Postal Code": "786 91",
  "Inferred Country ISO2 Code": "SE",
  "Confidence Score": ""
}
Index: 157, Address:  Main Street,   Galoya Junction,   North central  Polonnaruwa  51375
{
  "Number": "51375",
  "Street": "Main Street",
  "Region": "North central",
  "City": "Polonnaruwa",
  "State": "Galoya Junction",
  "Province": "Polonnaruwa",
  "District": "North central",
  "Postal Code": "51375",
  "Inferred Country ISO2 Code": "LK",
  "Confidence Score": "data not available"
}
Index: 158, Address:  Jido-Ro 49beon-Gil, Gyeonggi, Todang-Dong  , ,   10510
{
  "Number": "49beon-Gil",
  "Street": "Jido-Ro",
  "Region": "Gyeonggi",
  "City": "Todang-Dong",
  "State": " (no state listed)",
  "Province": " (no province listed)",
  "District": " (no district listed)",
  "Postal Code": "10510",
  "Inferred Country ISO2 Code": "KR",
  "Confidence Score": "High"
}
Index: 159, Address:  Rua 1, Goiás, Goiânia,       74553-045
{
  "Number": "Andar 1",
  "Street": "Rua",
  "Region": "Goi\u00e1s",
  "City": "Goi\u00e2nia",
  "State": "Goi\u00e1s",
  "Province": "Central West",
  "District": "no district given",
  "Postal Code": "74553-045",
  "Inferred Country ISO2 Code": "BR",
  "Confidence Score": "As it contains a postal code it is likely to be from Brazil."
}
Index: 160, Address:  Carretera a Playa Juan Francisco, Villa Clara  Chiqui Gómez    , ,
{
  "Number": "",
  "Street": "Carretera a Playa Juan Francisco",
  "Region": "Villa Clara",
  "City": "Chiqui G\u00f3mez",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "CU",
  "Confidence Score": "cuba"
}
Index: 161, Address:  Jinhae-daero 1041beon-gil  South Gyeongsang, Jinhae-gu, Changwon-si,   , , 51645
{
  "Number": "1041beon-gil",
  "Street": "Jinhae-daero",
  "Region": "South Gyeongsang",
  "City": "Jinhae-gu",
  "State": "Changwon-si",
  "Province": "None",
  "District": "None",
  "Postal Code": "51645",
  "Inferred Country ISO2 Code": "KR",
  "Confidence Score": "url"
}
Index: 162, Address:  'Erod, Southern  Eilat,   , , 88206 73
{
  "Number": "Erod",
  "Street": "Southern",
  "Region": "Eilat",
  "City": "",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "88206 73",
  "Inferred Country ISO2 Code": "IL",
  "Confidence Score": "/5"
}
Index: 163, Address:  شارع 6  أبوظبي  أبوظبي  , , , 22401
{
  "Number": "6",
  "Street": "",
  "Region": "\u0623\u0628\u0648\u0638\u0628\u064a",
  "City": "\u0623\u0628\u0648\u0638\u0628\u064a",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "22401",
  "Inferred Country ISO2 Code": "AE",
  "Confidence Score": ""
}
Index: 164, Address:  Gbemisola St.  , Abeokuta  Ogun State  ,   110213
{
  "Number": "Gbemisola St.",
  "Street": "",
  "Region": "Abeokuta",
  "City": "Ogun State",
  "State": "Nigeria",
  "Province": "",
  "District": "",
  "Postal Code": "110213",
  "Inferred Country ISO2 Code": "NG",
  "Confidence Score": "Medium"
}
Index: 165, Address:  AH1-AH2  Sagaing, Sagaing Township, ,   ,
{
  "Number": "AH1-AH2",
  "Street": "",
  "Region": "Sagaing",
  "City": "Sagaing Township",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "",
  "Confidence Score": ""
}
Index: 166, Address:  Main Street  , Morahela  , Sabaragamuwa  Ratnapura, 70129
{
  "Number": "70129",
  "Street": "Main Street",
  "Region": "Sabaragamuwa",
  "City": "Ratnapura",
  "State": "Morahela",
  "Province": "Sabaragamuwa",
  "District": "Ratnapura",
  "Postal Code": "70129",
  "Inferred Country ISO2 Code": "LK",
  "Confidence Score": "These values are based on a heuristic and may not be accurate for all addresses."
}
Index: 167, Address:  Eqnm 5/7  Distrito Federal  Brasília, ,   , 72215-540
{
  "Number": "5/7",
  "Street": "Eqnm",
  "Region": "Distrito Federal",
  "City": "Bras\u00edlia",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "72215-540",
  "Inferred Country ISO2 Code": "BR",
  "Confidence Score": "default"
}
Index: 168, Address:  Badalashvili V Dr, Lower Kartli, Manglisi
{
  "Number": "Badalashvili V Dr",
  "Street": "",
  "Region": "Lower Kartli",
  "City": "Manglisi",
  "State": "",
  "Province": "Kartli",
  "District": "",
  "Postal Code": "",
  "Inferred Country ISO2 Code": "GE",
  "Confidence Score": "urlparse"
}
Index: 169, Address:  Таежная ул  Хакасия Респ, Сорск г, , , , 655111
{
  "Number": "655111",
  "Street": "Ta\u0435zhnaya",
  "Region": "Khakasya",
  "City": "Sorsk",
  "State": "Respublika Khakasya",
  "Province": "Khakasya",
  "District": "",
  "Postal Code": "655111",
  "Inferred Country ISO2 Code": "RU",
  "Confidence Score": "c98"
}
Index: 170, Address:  Поляна Манунская ул, Воронежская обл  Гремячье с    ,   396813
{
  "Number": "396813",
  "Street": "\u041f\u043e\u043b\u044f\u043d\u0430 \u041c\u0430\u043d\u0443\u043d\u0441\u043a\u0430\u044f \u0443\u043b",
  "Region": "\u0412\u043e\u0440\u043e\u043d\u0435\u0436\u0441\u043a\u0430\u044f \u043e\u0431\u043b",
  "City": "\u0413\u0440\u0435\u043c\u044f\u0447\u044c\u0435 \u0441",
  "State": "unknown",
  "Province": "unknown",
  "District": "unknown",
  "Postal Code": "396813",
  "Inferred Country ISO2 Code": "ru",
  "Confidence Score": "0.8"
}
Index: 171, Address:  Jakobs väg  Skåne  Kristianstad,   , , 291 60
{
  "Number": "291 60",
  "Street": "Jakobs v\u00e4g",
  "Region": "Sk\u00e5ne",
  "City": "Kristianstad",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "291 60",
  "Inferred Country ISO2 Code": "SE",
  "Confidence Score": "classify as a swedish address"
}
Index: 172, Address:  Calle Tab  Buenos Aires, Coronel Pringles,     , B7530 EDM
{
  "Number": "B7530",
  "Street": "Calle Tab",
  "Region": "Buenos Aires",
  "City": "Coronel Pringles",
  "State": "",
  "Province": "",
  "District": "",
  "Postal Code": "B7530",
  "Inferred Country ISO2 Code": "AR",
  "Confidence Score": ""
}
Index: 173, Address:  Carretera Minas - Sola  Camagüey, Pueblo de Sola    ,
{
  "Number": "Carretera Minas - Sola",
  "Street": "Camag\u00fcey",
  "Region": "Pueblo de Sola",
  "City": "Camag\u00fcey",
  "State": "Camag\u00fcey Province",
  "Province": "Camag\u00fcey",
  "District": "Pueblo de Sola",
  "Postal Code": " ",
  "Inferred Country ISO2 Code": "CU",
  "Confidence Score": "0.98"
}
Index: 174, Address:  Jukdong-gil 424beon-gil  Busan  Gangseo-gu  , ,   46708
{
  "Number": ",",
  "Street": "Jukdong-gil",
  "Region": "Busan",
  "City": "Gangseo-gu",
  "State": "",
  "Province": "",
  "District": "424beon-gil",
  "Postal Code": "46708",
  "Inferred Country ISO2 Code": "KR",
  "Confidence Score": ","
}
Index: 175, Address:  Suleja Rd.,   Bida  Niger State, , , 912232
{
  "Number": "912232",
  "Street": "Suleja Rd.",
  "Region": "Niger State",
  "City": "Bida",
  "State": "Niger State",
  "Province": "Niger State",
  "District": "Niger State",
  "Postal Code": "912232",

In [167]:
df1.head(n=15)

,index,MessageType,CountryCodeVerified,Address,Number,Street,Region,City,State,Province,PostalCode,CountryCodeLLM,ConfidenceScore
0,2014,pacs.008,AE,"151 Street Sharjah, Sharjah, ,",151,Street,Sharjah,Sharjah,,,,AE,Some
1,1683,pacs.008,ES,"Caserio el Rebellon, Principado de Asturias, Godella, 33758",33758,Caserio el Rebellon,Principado de Asturias,Godella,Asturias,Asturias,33758,ES,1
2,2281,pacs.008,YE,"طريق الجبجب الثلوث, Dhamar Governorate, Al Hudayyah,",,الجبجب الثلوث,Dhamar Governorate,Al Hudayyah,,,,YE,For more information visit: https://nominatim.openstreetmap.org/search?q=الجبجب%20الثلوث%20Dhamar%20Governorate%20Al%20Hudayyah&format=json&limit=1
3,1691,pacs.008,ES,"Calle Bosc, Cataluña, Rubí , , 8191",",",Calle Bosc,Cataluña,Rubí,,,8191,ES,"catalonia is not a city, but a region, and Rubi is a city in the region."
4,736,pacs.008,IL,"Nitsanim Haifa Haifa , , 34354 37",: 34354,Nitsanim,Haifa,Haifa,,,34354,IL,: 0.2
5,196,pacs.008,BY,"Пограничная полоса Border Line Grodno Region Сопоцкинский сельский Совет, , ,",Пограничная полоса,Border Line,Grodno Region,Сопоцкинский сельский Совет,,,,BY,0.8
6,482,pacs.008,CU,"Carretera Central Guantánamo, Baitiqurí, , ,",Carretera Central,Carretera Central,Guantánamo,Baitiqurí,Guantánamo,Guantánamo,,CU,Medium
7,1675,pacs.008,ES,"Diseminado Afores Cataluña, Pegueroles , , 25286",25286,Diseminado Afores,Cataluña,Pegueroles,,,25286,ES,Implicit
8,435,pacs.008,CU,"Carretera Sancti Spiritus - Yaguajay Sancti Spiritus, Jíquima de Peláez , ,",,Carretera Sancti Spiritus - Yaguajay,Sancti Spiritus,Jíquima de Peláez,,,,,}
9,555,pacs.008,GE,"ზუგდიდი-ჯვარი-მესტია-ლასდილი, Samegrelo-Upper Svaneti Zeda Etseri, , , ,","} ZUGDIDI-ჯვარი-მესტია-ლასდილი, Samegrelo-Upper Svaneti",Zeda Etseri,,Zugdidi,Samegrelo-Upper Svaneti,,,,}
10,2044,pacs.008,AE,"شارع محمد بن مطر الفجيرة, الفجيرة ,",,القادح الإثن الالاكالي,فجيرة,فجيرة,,,,,Not Given
11,179,pacs.008,BY,"Бывшая УЖД ""Большие Чучевичи - Гоцк"" Minsk Region Копацевичский сельский Совет, ,",Бывшая УЖД,Большие Чучевичи,Minsk Region,Гоцк,None,Копацевичский сельский Совет,None,None,x
12,1708,pacs.008,LK,"Main Street, Dewanagala Sabaragamuwa Kegalle, 71527",71527,Main Street,Sabaragamuwa,Dewanagala,Kegalle,Sabaragamuwa,71527,LK,0.7
13,457,pacs.008,CU,"Carretera Cifuentes - Calabazar de Sagua Villa Clara Calabazar de Sagua, , ,",,Carretera,Cifuentes - Calabazar de Sagua,Villa Clara,,,,CU,"name: 0.995, state: 0.005, province: 0.005, district: 0.995"
14,1459,pacs.008,SO,"Dhahar Highway, Sanaag, Dhahar , ,",,Dhahar Highway,Sanaag,Dhahar,,,,,} }

# Phase 2: Validate Phase 2 Result Against GeoNames Database
<b> <font face="Verdana" size="3"> Objective: </font></b><br>
Since the precision and accuracy rates of Llama will never be 100% on messy addresses, it is neccessary to validate the result against a secondary country deciphering method. This method uses the address components parsed by the Llama model as parameters and search for the best matching country in the GeoNames database.

In [168]:
##############################################################################################
# Purpose:
# This function returns the most frequently occurring value in a one dimensional numpy array.
##############################################################################################

def MostFrequentArrItem(arr=None):
    if arr.size == 0:
        return None

    frequency_map = {}
    max_count = 0
    most_frequent_item = None

    for item in arr:
        frequency_map[item] = frequency_map.get(item, 0) + 1
        if frequency_map[item] > max_count:
            max_count = frequency_map[item]
            most_frequent_item = item

    return most_frequent_item

In [169]:
##############################################################################################
# Purpose:
# This function searches for the best match country in the GeoNames database.
# Inpute parameters:
# An array of street number, street name, region name, city name, state name, and postal code.
##############################################################################################

def GeonamesCountrySearch(INarr=None, username=None):
    # GeoNames free search API endpoint
    base_url = "http://api.geonames.org/searchJSON"
    #base_url = "http://geonames.org"

    # splitting the input array of address components into 9 search combinations
    search_query1 = INarr[0:5].astype(str)
    search_query2 = INarr[1:3].astype(str)
    search_query3 = INarr[1:4].astype(str)
    search_query4 = INarr[1:5].astype(str)
    search_query5 = INarr[2:4].astype(str)
    search_query6 = INarr[2:5].astype(str)
    search_query7 = INarr[3:5].astype(str)
    search_query8 = INarr[[1,3]].astype(str)
    search_query9 = INarr[[1,4]].astype(str)

    # producing search strings by concetenating address components with comma delimiter
    search_query1_f = ",".join(search_query1[search_query1 != ""])
    search_query2_f = ",".join(search_query2[search_query2 != ""])
    search_query3_f = ",".join(search_query3[search_query3 != ""])
    search_query4_f = ",".join(search_query4[search_query4 != ""])
    search_query5_f = ",".join(search_query5[search_query5 != ""])
    search_query6_f = ",".join(search_query6[search_query6 != ""])
    search_query7_f = ",".join(search_query7[search_query7 != ""])
    search_query8_f = ",".join(search_query8[search_query8 != ""])
    search_query9_f = ",".join(search_query9[search_query9 != ""])

    # storing the 9 search strings in an array
    SrcArr = [search_query1_f,
              search_query2_f,
              search_query3_f,
              search_query4_f,
              search_query5_f,
              search_query6_f,
              search_query7_f,
              search_query8_f,
              search_query9_f]

    # Search GeoNames for all 9 possible of address combinations.
    # Store all 90 (10 outcomes for each of the 9 searches) possible countries into an array.
    # Returns the most frequently found country.

    i=0
    my_array = np.array([])

    for item in SrcArr:
        print (f"Address Part: {item}")
        params = {
            "q": item,
            #"name_equals": item,
            "maxRows": 10,           # We only need the top/most accurate match
            "username": username,    # Your activated GeoNames username
            "fuzzy": 1
        }
        response = requests.get(base_url, params=params)
        response.raise_for_status() # Raise exception for bad status codes
        data = response.json()

        if data.get('geonames'): # Check if the API returned any results
            result = data.get('geonames')
            temp_list = []
            for geoname in result:
                i=i+1
                print(f"GeoNames Result#{i} - Address Part: {geoname.get('name')}, Country: {geoname.get('countryCode')}")
                temp_list.append(geoname.get('countryCode'))
            my_array = np.array(temp_list)

    if my_array.size == 0:
        return None
    else:
        # Returns the most frequently found country.
        return MostFrequentArrItem(my_array)

In [170]:
############################################################
# Executing Phase 2
############################################################

USERNAME = "henryjhu"
df1['CountryCodeGeoNames'] = ''
i=0
# Record the process start time
start_time = time.perf_counter()
for row in df1.itertuples(index=True):
    i=i+1
    print (f"Address#{i} Begin")
    country = GeonamesCountrySearch(np.array([row.Number, row.Street, row.City, row.State, row.Region, row.PostalCode]), USERNAME)
    if (not(country)) or (country == "None"): country = "Unknown"
    print (f"Address#{i} GeoNames Country: {country}")
    df1.at[row.Index,'CountryCodeGeoNames' ] = country
# Record the process end time
end_time = time.perf_counter()
# Calculate process elapsed time
execution_time = end_time - start_time
print(f"Execution time: {execution_time:.6f} seconds")

Streaming output truncated to the last 5000 lines.
GeoNames Result#7 - Address Part: Main-Yankee Street Historic District, Country: US
GeoNames Result#8 - Address Part: Main Street Commercial District, Country: US
GeoNames Result#9 - Address Part: Pinson Main Street Historic District, Country: US
GeoNames Result#10 - Address Part: Main Street Historic District, Country: US
GeoNames Result#11 - Address Part: Main Street Historic District, Country: US
GeoNames Result#12 - Address Part: Fort Payne Main Street Historic District, Country: US
GeoNames Result#13 - Address Part: Main Street Historic District, Country: US
Address#35 GeoNames Country: US
Address#36 Begin
Address Part: 49beon-Gil,Jido-Ro,Todang-Dong, (no state listed),Gyeonggi
Address Part: Jido-Ro,Todang-Dong
Address Part: Jido-Ro,Todang-Dong, (no state listed)
Address Part: Jido-Ro,Todang-Dong, (no state listed),Gyeonggi
Address Part: Todang-Dong, (no state listed)
Address Part: Todang-Dong, (no state listed),Gyeonggi
Address Part:  (no state listed),Gyeonggi
Address Part: Jido-Ro, (no state listed)
Address Part: Jido-Ro,Gyeonggi
Address#36 GeoNames Country: Unknown
Address#37 Begin
Address Part: Andar 1,Rua,Goiânia,Goiás,Goiás
Address Part: Rua,Goiânia
Address Part: Rua,Goiânia,Goiás
Address Part: Rua,Goiânia,Goiás,Goiás
Address Part: Goiânia,Goiás
GeoNames Result#1 - Address Part: Goiânia, Country: BR
GeoNames Result#2 - Address Part: Aparecida de Goiânia, Country: BR
GeoNames Result#3 - Address Part: Santa Genoveva / Goiânia Airport, Country: BR
GeoNames Result#4 - Address Part: Goiânia, Country: BR
GeoNames Result#5 - Address Part: Aparecida de Goiânia, Country: BR
GeoNames Result#6 - Address Part: Pedroso, Country: BR
GeoNames Result#7 - Address Part: Serra das Areias, Country: BR
GeoNames Result#8 - Address Part: Vila Rica, Country: BR
GeoNames Result#9 - Address Part: Bom Retiro, Country: BR
GeoNames Result#10 - Address Part: Setor Marista, Country: BR
Address Part: Goiânia,Goiás,Goiás
GeoNames Result#11 - Address Part: Goiânia, Country: BR
GeoNames Result#12 - Address Part: Aparecida de Goiânia, Country: BR
GeoNames Result#13 - Address Part: Santa Genoveva / Goiânia Airport, Country: BR
GeoNames Result#14 - Address Part: Goiânia, Country: BR
GeoNames Result#15 - Address Part: Aparecida de Goiânia, Country: BR
GeoNames Result#16 - Address Part: Pedroso, Country: BR
GeoNames Result#17 - Address Part: Serra das Areias, Country: BR
GeoNames Result#18 - Address Part: Vila Rica, Country: BR
GeoNames Result#19 - Address Part: Bom Retiro, Country: BR
GeoNames Result#20 - Address Part: Setor Marista, Country: BR
Address Part: Goiás,Goiás
GeoNames Result#21 - Address Part: Goiás, Country: BR
GeoNames Result#22 - Address Part: Goiânia, Country: BR
GeoNames Result#23 - Address Part: Águas Lindas de Goiás, Country: BR
GeoNames Result#24 - Address Part: Valparaíso de Goiás, Country: BR
GeoNames Result#25 - Address Part: Anápolis, Country: BR
GeoNames Result#26 - Address Part: Trindade, Country: BR
GeoNames Result#27 - Address Part: Planaltina, Country: BR
GeoNames Result#28 - Address Part: Luziânia, Country: BR
GeoNames Result#29 - Address Part: Catalão, Country: BR
GeoNames Result#30 - Address Part: Rio Verde, Country: BR
Address Part: Rua,Goiás
GeoNames Result#31 - Address Part: Fazenda Bom Jesus do Ruá, Country: BR
GeoNames Result#32 - Address Part: Córrego Ruá, Country: BR
GeoNames Result#33 - Address Part: Córrego da Rua, Country: BR
Address Part: Rua,Goiás
GeoNames Result#34 - Address Part: Fazenda Bom Jesus do Ruá, Country: BR
GeoNames Result#35 - Address Part: Córrego Ruá, Country: BR
GeoNames Result#36 - Address Part: Córrego da Rua, Country: BR
Address#37 GeoNames Country: BR
Address#38 Begin
Address Part: Carretera a Playa Juan Francisco,Chiqui Gómez,Villa Clara
Address Part: Carretera a Playa Juan Francisco,Chiqui Gómez
Address Part: Carretera a Playa Juan Francisco,Chiqui Gómez
Address Part: Carretera a Playa Juan Francisco,Chiqui Gómez,Villa Clara
Address Part: Chiqui Gómez
GeoNames Result#1 - Address Part: Chiqui Gómez, Country: CU
GeoNames Result#2 - Address Part: Jutiero, Country: CU
Address Part: Chiqui Gómez,Villa Clara
GeoNames Result#3 - Address Part: Jutiero, Country: CU
GeoNames Result#4 - Address Part: Chiqui Gómez, Country: CU
Address Part: Villa Clara
GeoNames Result#5 - Address Part: Santa Clara, Country: CU
GeoNames Result#6 - Address Part: Villa Clara Province, Country: CU
GeoNames Result#7 - Address Part: Abel Santamaría Airport, Country: CU
GeoNames Result#8 - Address Part: Corralillo, Country: CU
GeoNames Result#9 - Address Part: Caibarién, Country: CU
GeoNames Result#10 - Address Part: Placetas, Country: CU
GeoNames Result#11 - Address Part: Las Brujas Airport, Country: CU
GeoNames Result#12 - Address Part: Municipio de Santa Clara, Country: CU
GeoNames Result#13 - Address Part: Isabela de Sagua, Country: CU
GeoNames Result#14 - Address Part: Esperanza, Country: CU
Address Part: Carretera a Playa Juan Francisco
Address Part: Carretera a Playa Juan Francisco,Villa Clara
Address#38 GeoNames Country: CU
Address#39 Begin
Address Part: 1041beon-gil,Jinhae-daero,Jinhae-gu,Changwon-si,South Gyeongsang
Address Part: Jinhae-daero,Jinhae-gu
Address Part: Jinhae-daero,Jinhae-gu,Changwon-si
Address Part: Jinhae-daero,Jinhae-gu,Changwon-si,South Gyeongsang
Address Part: Jinhae-gu,Changwon-si
GeoNames Result#1 - Address Part: Jinhae Airport, Country: KR
GeoNames Result#2 - Address Part: Jinhae-gu, Country: KR
GeoNames Result#3 - Address Part: Buindang, Country: KR
GeoNames Result#4 - Address Part: Daejangdong, Country: KR
GeoNames Result#5 - Address Part: Yongjae, Country: KR
GeoNames Result#6 - Address Part: Punghogongwon, Country: KR
GeoNames Result#7 - Address Part: Kotchuri San, Country: KR
GeoNames Result#8 - Address Part: Cheonjabong, Country: KR
GeoNames Result#9 - Address Part: Macheon, Country: KR
GeoNames Result#10 - Address Part: Bongdongsan, Country: KR
Address Part: Jinhae-gu,Changwon-si,South Gyeongsang
GeoNames Result#11 - Address Part: Jinhae Airport, Country: KR
GeoNames Result#12 - Address Part: Jinhae-gu, Country: KR
GeoNames Result#13 - Address Part: Buindang, Country: KR
GeoNames Result#14 - Address Part: Daejangdong, Country: KR
GeoNames Result#15 - Address Part: Yongjae, Country: KR
GeoNames Result#16 - Address Part: Punghogongwon, Country: KR
GeoNames Result#17 - Address Part: Kotchuri San, Country: KR
GeoNames Result#18 - Address Part: Cheonjabong, Country: KR
GeoNames Result#19 - Address Part: Macheon, Country: KR
GeoNames Result#20 - Address Part: Bongdongsan, Country: KR
Address Part: Changwon-si,South Gyeongsang
GeoNames Result#21 - Address Part: Changwon, Country: KR
GeoNames Result#22 - Address Part: Changwon-si, Country: KR
GeoNames Result#23 - Address Part: Naesŏ, Country: KR
GeoNames Result#24 - Address Part: Jinhae Airport, Country: KR
GeoNames Result#25 - Address Part: Changpo-ri, Country: KR
GeoNames Result#26 - Address Part: Buindang, Country: KR
GeoNames Result#27 - Address Part: Daejangdong, Country: KR
GeoNames Result#28 - Address Part: Sujŏng-ni, Country: KR
GeoNames Result#29 - Address Part: Sŏbuk-san, Country: KR
GeoNames Result#30 - Address Part: Sinchon-ri, Country: KR
Address Part: Jinhae-daero,Changwon-si
Address Part: Jinhae-daero,South Gyeongsang
Address#39 GeoNames Country: KR
Address#40 Begin
Address Part: Erod,Southern,Eilat
Address Part: Southern
GeoNames Result#1 - Address Part: Southern Asia, Country: None
GeoNames Result#2 - Address Part: Southern Asia, Country: IN
GeoNames Result#3 - Address Part: Southern Europe, Country: None
GeoNames Result#4 - Address Part: Southern Africa, Country: None
GeoNames Result#5 - Address Part: South, Country: US
GeoNames Result#6 - Address Part: Region 2, Country: IR
GeoNames Result#7 - Address Part: Region 3, Country: IR
GeoNames Result#8 - Address Part: Region 4, Country: IR
GeoNames Result#9 - Address Part: Region 5, Country: IR
GeoNames Result#10 - Address Part: Mezzogiorno, Country: IT
Address Part: Southern
GeoNames Result#11 - Address Part: Southern Asia, Country: None
GeoNames Result#12 - Address Part: Southern Asia, Country: IN
GeoNames Result#13 - Address Part: Southern Europe, Country: None
GeoNames Result#14 - Address Part: Southern Africa, Country: None
GeoNames Result#15 - Address Part: South, Country: US
GeoNames Result#16 - Address Part: Region 2, Country: IR
GeoNames Result#17 - Address Part: Region 3, Country: IR
GeoNames Result#18 - Address Part: Region 4, Country: IR
GeoNames Result#19 - Address Part: Region 5, Country: IR
GeoNames Result#20 - Address Part: Mezzogiorno, Country: IT
Address Part: Southern,Eilat
GeoNames Result#21 - Address Part: Eilat, Country: IL
GeoNames Result#22 - Address Part: Eilat Airport, Country: IL
GeoNames Result#23 - Address Part: Ramon Airport, Country: IL
GeoNames Result#24 - Address Part: Shemurat Masiv Eilat, Country: IL
GeoNames Result#25 - Address Part: Ma‘ale Eilat, Country: IL
GeoNames Result#26 - Address Part: Nemal Elat, Country: IL
GeoNames Result#27 - Address Part: H̱of Eilat, Country: IL
GeoNames Result#28 - Address Part: Ovda Airport, Country: IL
GeoNames Result#29 - Address Part: Shmurat Massiv Elat, Country: IL
GeoNames Result#30 - Address Part: Elat, Country: IL
Address Part:
GeoNames Result#31 - Address Part: Rock Tower Well, Country: US
GeoNames Result#32 - Address Part: Rodkey, Country: US
GeoNames Result#33 - Address Part: Rodgers Cemetery, Country: US
GeoNames Result#34 - Address Part: Rolla Cemetery, Country: US
GeoNames Result#35 - Address Part: Rolla Elementary School, Country: US
GeoNames Result#36 - Address Part: Rolla Junior High / High School, Country: US
GeoNames Result#37 - Address Part: Rolla Township, Country: US
GeoNames Result#38 - Address Part: Rollo Pasture, Country: US
GeoNames Result#39 - Address Part: Roosevelt Township, Country: US
GeoNames Result#40 - Address Part: Rose Creek, Country: US
Address Part: Eilat
GeoNames Result#41 - Address Part: Eilat, Country: IL
GeoNames Result#42 - Address Part: Eilat Airport, Country: IL
GeoNames Result#43 - Address Part: Ramon Airport, Country: IL
GeoNames Result#44 - Address Part: Gulf of Aqaba, Country: None
GeoNames Result#45 - Address Part: Ma‘avar Gevul Taba, Country: EG
GeoNames Result#46 - Address Part: Shemurat Masiv Eilat, Country: IL
GeoNames Result#47 - Address Part: Ma‘ale Eilat, Country: IL
GeoNames Result#48 - Address Part: Nemal Elat, Country: IL
GeoNames Result#49 - Address Part: H̱of Eilat, Country: IL
GeoNames Result#50 - Address Part: Ovda Airport, Country: IL
Address Part: Eilat
GeoNames Result#51 - Address Part: Eilat, Country: IL
GeoNames Result#52 - Address Part: Eilat Airport, Country: IL
GeoNames Result#53 - Address Part: Ramon Airport, Country: IL
GeoNames Result#54 - Address Part: Gulf of Aqaba, Country: None
GeoNames Result#55 - Address Part: Ma‘avar Gevul Taba, Country: EG
GeoNames Result#56 - Address Part: Shemurat Masiv Eilat, Country: IL
GeoNames Result#57 - Address Part: Ma‘ale Eilat, Country: IL
GeoNames Result#58 - Address Part: Nemal Elat, Country: IL
GeoNames Result#59 - Address Part: H̱of Eilat, Country: IL
GeoNames Result#60 - Address Part: Ovda Airport, Country: IL
Address Part: Southern
GeoNames Result#61 - Address Part: Southern Asia, Country: None
GeoNames Result#62 - Address Part: Southern Asia, Country: IN
GeoNames Result#63 - Address Part: Southern Europe, Country: None
GeoNames Result#64 - Address Part: Southern Africa, Country: None
GeoNames Result#65 - Address Part: South, Country: US
GeoNames Result#66 - Address Part: Region 2, Country: IR
GeoNames Result#67 - Address Part: Region 3, Country: IR
GeoNames Result#68 - Address Part: Region 4, Country: IR
GeoNames Result#69 - Address Part: Region 5, Country: IR
GeoNames Result#70 - Address Part: Mezzogiorno, Country: IT
Address Part: Southern,Eilat
GeoNames Result#71 - Address Part: Eilat, Country: IL
GeoNames Result#72 - Address Part: Eilat Airport, Country: IL
GeoNames Result#73 - Address Part: Ramon Airport, Country: IL
GeoNames Result#74 - Address Part: Shemurat Masiv Eilat, Country: IL
GeoNames Result#75 - Address Part: Ma‘ale Eilat, Country: IL
GeoNames Result#76 - Address Part: Nemal Elat, Country: IL
GeoNames Result#77 - Address Part: H̱of Eilat, Country: IL
GeoNames Result#78 - Address Part: Ovda Airport, Country: IL
GeoNames Result#79 - Address Part: Shmurat Massiv Elat, Country: IL
GeoNames Result#80 - Address Part: Elat, Country: IL
Address#40 GeoNames Country: IL
Address#41 Begin
Address Part: 6,أبوظبي,أبوظبي
GeoNames Result#1 - Address Part: Adg6, Country: AE
GeoNames Result#2 - Address Part: E6, Country: AE
GeoNames Result#3 - Address Part: W6, Country: AE
GeoNames Result#4 - Address Part: Mn6, Country: AE
GeoNames Result#5 - Address Part: Sw6, Country: AE
GeoNames Result#6 - Address Part: Rs6, Country: AE
GeoNames Result#7 - Address Part: Mi6, Country: AE
GeoNames Result#8 - Address Part: Khia6, Country: AE
GeoNames Result#9 - Address Part: Msh6, Country: AE
GeoNames Result#10 - Address Part: Mq6, Country: AE
Address Part: أبوظبي
GeoNames Result#11 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#12 - Address Part: Al Ain City, Country: AE
GeoNames Result#13 - Address Part: Musaffah City, Country: AE
GeoNames Result#14 - Address Part: Khalifah A City, Country: AE
GeoNames Result#15 - Address Part: Abu Dhabi International Airport, Country: AE
GeoNames Result#16 - Address Part: Bani Yas City, Country: AE
GeoNames Result#17 - Address Part: Al Bateen Executive Airport, Country: AE
GeoNames Result#18 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#19 - Address Part: Zayed City, Country: AE
GeoNames Result#20 - Address Part: Liwa Oasis, Country: AE
Address Part: أبوظبي
GeoNames Result#21 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#22 - Address Part: Al Ain City, Country: AE
GeoNames Result#23 - Address Part: Musaffah City, Country: AE
GeoNames Result#24 - Address Part: Khalifah A City, Country: AE
GeoNames Result#25 - Address Part: Abu Dhabi International Airport, Country: AE
GeoNames Result#26 - Address Part: Bani Yas City, Country: AE
GeoNames Result#27 - Address Part: Al Bateen Executive Airport, Country: AE
GeoNames Result#28 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#29 - Address Part: Zayed City, Country: AE
GeoNames Result#30 - Address Part: Liwa Oasis, Country: AE
Address Part: أبوظبي,أبوظبي
GeoNames Result#31 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#32 - Address Part: Al Ain City, Country: AE
GeoNames Result#33 - Address Part: Musaffah City, Country: AE
GeoNames Result#34 - Address Part: Khalifah A City, Country: AE
GeoNames Result#35 - Address Part: Abu Dhabi International Airport, Country: AE
GeoNames Result#36 - Address Part: Bani Yas City, Country: AE
GeoNames Result#37 - Address Part: Al Bateen Executive Airport, Country: AE
GeoNames Result#38 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#39 - Address Part: Zayed City, Country: AE
GeoNames Result#40 - Address Part: Liwa Oasis, Country: AE
Address Part: أبوظبي
GeoNames Result#41 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#42 - Address Part: Al Ain City, Country: AE
GeoNames Result#43 - Address Part: Musaffah City, Country: AE
GeoNames Result#44 - Address Part: Khalifah A City, Country: AE
GeoNames Result#45 - Address Part: Abu Dhabi International Airport, Country: AE
GeoNames Result#46 - Address Part: Bani Yas City, Country: AE
GeoNames Result#47 - Address Part: Al Bateen Executive Airport, Country: AE
GeoNames Result#48 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#49 - Address Part: Zayed City, Country: AE
GeoNames Result#50 - Address Part: Liwa Oasis, Country: AE
Address Part: أبوظبي,أبوظبي
GeoNames Result#51 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#52 - Address Part: Al Ain City, Country: AE
GeoNames Result#53 - Address Part: Musaffah City, Country: AE
GeoNames Result#54 - Address Part: Khalifah A City, Country: AE
GeoNames Result#55 - Address Part: Abu Dhabi International Airport, Country: AE
GeoNames Result#56 - Address Part: Bani Yas City, Country: AE
GeoNames Result#57 - Address Part: Al Bateen Executive Airport, Country: AE
GeoNames Result#58 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#59 - Address Part: Zayed City, Country: AE
GeoNames Result#60 - Address Part: Liwa Oasis, Country: AE
Address Part: أبوظبي
GeoNames Result#61 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#62 - Address Part: Al Ain City, Country: AE
GeoNames Result#63 - Address Part: Musaffah City, Country: AE
GeoNames Result#64 - Address Part: Khalifah A City, Country: AE
GeoNames Result#65 - Address Part: Abu Dhabi International Airport, Country: AE
GeoNames Result#66 - Address Part: Bani Yas City, Country: AE
GeoNames Result#67 - Address Part: Al Bateen Executive Airport, Country: AE
GeoNames Result#68 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#69 - Address Part: Zayed City, Country: AE
GeoNames Result#70 - Address Part: Liwa Oasis, Country: AE
Address Part:
GeoNames Result#71 - Address Part: Rock Tower Well, Country: US
GeoNames Result#72 - Address Part: Rodkey, Country: US
GeoNames Result#73 - Address Part: Rodgers Cemetery, Country: US
GeoNames Result#74 - Address Part: Rolla Cemetery, Country: US
GeoNames Result#75 - Address Part: Rolla Elementary School, Country: US
GeoNames Result#76 - Address Part: Rolla Junior High / High School, Country: US
GeoNames Result#77 - Address Part: Rolla Township, Country: US
GeoNames Result#78 - Address Part: Rollo Pasture, Country: US
GeoNames Result#79 - Address Part: Roosevelt Township, Country: US
GeoNames Result#80 - Address Part: Rose Creek, Country: US
Address Part: أبوظبي
GeoNames Result#81 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#82 - Address Part: Al Ain City, Country: AE
GeoNames Result#83 - Address Part: Musaffah City, Country: AE
GeoNames Result#84 - Address Part: Khalifah A City, Country: AE
GeoNames Result#85 - Address Part: Abu Dhabi International Airport, Country: AE
GeoNames Result#86 - Address Part: Bani Yas City, Country: AE
GeoNames Result#87 - Address Part: Al Bateen Executive Airport, Country: AE
GeoNames Result#88 - Address Part: Abu Dhabi, Country: AE
GeoNames Result#89 - Address Part: Zayed City, Country: AE
GeoNames Result#90 - Address Part: Liwa Oasis, Country: AE
Address#41 GeoNames Country: AE
Address#42 Begin
Address Part: Gbemisola St.,Ogun State,Nigeria,Abeokuta
Address Part: Ogun State
GeoNames Result#1 - Address Part: Abeokuta, Country: NG
GeoNames Result#2 - Address Part: Ogun State, Country: NG
GeoNames Result#3 - Address Part: Ijebu Ode, Country: NG
GeoNames Result#4 - Address Part: Ota, Country: NG
GeoNames Result#5 - Address Part: Ogun Waterside, Country: NG
GeoNames Result#6 - Address Part: Sagamu, Country: NG
GeoNames Result#7 - Address Part: Ijebu-Igbo, Country: NG
GeoNames Result#8 - Address Part: Ifo, Country: NG
GeoNames Result#9 - Address Part: Ado-Odo, Country: NG
GeoNames Result#10 - Address Part: Ilaro, Country: NG
Address Part: Ogun State,Nigeria
GeoNames Result#11 - Address Part: Abeokuta, Country: NG
GeoNames Result#12 - Address Part: Ogun State, Country: NG
GeoNames Result#13 - Address Part: Ijebu Ode, Country: NG
GeoNames Result#14 - Address Part: Ota, Country: NG
GeoNames Result#15 - Address Part: Ogun Waterside, Country: NG
GeoNames Result#16 - Address Part: Sagamu, Country: NG
GeoNames Result#17 - Address Part: Ijebu-Igbo, Country: NG
GeoNames Result#18 - Address Part: Ifo, Country: NG
GeoNames Result#19 - Address Part: Ado-Odo, Country: NG
GeoNames Result#20 - Address Part: Ilaro, Country: NG
Address Part: Ogun State,Nigeria,Abeokuta
GeoNames Result#21 - Address Part: Abeokuta, Country: NG
GeoNames Result#22 - Address Part: Abeokuta South, Country: NG
GeoNames Result#23 - Address Part: Abeokuta North, Country: NG
GeoNames Result#24 - Address Part: Ibara-Orile, Country: NG
GeoNames Result#25 - Address Part: Eniagbe-Olateju, Country: NG

In [171]:
# Examine the first 5 rows of the dataframe
df1.head(n=5)

,index,MessageType,CountryCodeVerified,Address,Number,Street,Region,City,State,Province,PostalCode,CountryCodeLLM,ConfidenceScore,CountryCodeGeoNames
0,2014,pacs.008,AE,"151 Street Sharjah, Sharjah, ,",151,Street,Sharjah,Sharjah,,,,AE,Some,LC
1,1683,pacs.008,ES,"Caserio el Rebellon, Principado de Asturias, Godella, 33758",33758,Caserio el Rebellon,Principado de Asturias,Godella,Asturias,Asturias,33758,ES,1,ES
2,2281,pacs.008,YE,"طريق الجبجب الثلوث, Dhamar Governorate, Al Hudayyah,",,الجبجب الثلوث,Dhamar Governorate,Al Hudayyah,,,,YE,For more information visit: https://nominatim.openstreetmap.org/search?q=الجبجب%20الثلوث%20Dhamar%20Governorate%20Al%20Hudayyah&format=json&limit=1,YE
3,1691,pacs.008,ES,"Calle Bosc, Cataluña, Rubí , , 8191",",",Calle Bosc,Cataluña,Rubí,,,8191,ES,"catalonia is not a city, but a region, and Rubi is a city in the region.",ES
4,736,pacs.008,IL,"Nitsanim Haifa Haifa , , 34354 37",: 34354,Nitsanim,Haifa,Haifa,,,34354,IL,: 0.2,IL

# Phase 3: Reducing The Number of Incorrect Results

In [173]:
df1['CountryCodeFinal'] = ''

# Iterate through the entire df1 dataframe
for idx, row in df1.iterrows():
    #Exracting the values of each field and convert them into strings.
    ctryLLM = str(row['CountryCodeLLM'])
    ctryGEO = str(row['CountryCodeGeoNames'])

    # remove special characters from field CountryCodeLLM
    replacements = {".": " ", "'": " ",'"': " ","\n": " ","\\n": " ","\t": " ","\\": " "}
    for old, new in replacements.items():
        ctryLLM = ctryLLM.replace(old, new).strip()

    # Logic to figure out what the final country code should be.
    if ctryLLM == ctryGEO:
        df1.iloc[idx,14] = ctryGEO
    elif (ctryLLM == 'unspecified')  & (ctryGEO == 'Unknown'):
        df1.iloc[idx,14] = 'Unknown'
    elif (ctryLLM == '(none)')  & (ctryGEO == 'Unknown'):
        df1.iloc[idx,14] = 'Unknown'
    elif (pd.isna(ctryLLM))  & (ctryGEO == 'Unknown'):
        df1.iloc[idx,14] = 'Unknown'
    elif (not pd.isna(ctryLLM))  & (ctryGEO == 'Unknown'):
        df1.iloc[idx,14] = ctryLLM
    elif (pd.isna(ctryLLM))  & (ctryGEO != 'Unknown'):
        df1.iloc[idx,14] = ctryGEO
    elif ctryLLM != ctryGEO:
        df1.iloc[idx,14] = ctryGEO
    else:
        df1.iloc[idx,14] = 'Unknown'

In [174]:
# Examine the first 5 rows of the dataframe
df1.head(n=5)

,index,MessageType,CountryCodeVerified,Address,Number,Street,Region,City,State,Province,PostalCode,CountryCodeLLM,ConfidenceScore,CountryCodeGeoNames,CountryCodeFinal
0,2014,pacs.008,AE,"151 Street Sharjah, Sharjah, ,",151,Street,Sharjah,Sharjah,,,,AE,Some,LC,LC
1,1683,pacs.008,ES,"Caserio el Rebellon, Principado de Asturias, Godella, 33758",33758,Caserio el Rebellon,Principado de Asturias,Godella,Asturias,Asturias,33758,ES,1,ES,ES
2,2281,pacs.008,YE,"طريق الجبجب الثلوث, Dhamar Governorate, Al Hudayyah,",,الجبجب الثلوث,Dhamar Governorate,Al Hudayyah,,,,YE,For more information visit: https://nominatim.openstreetmap.org/search?q=الجبجب%20الثلوث%20Dhamar%20Governorate%20Al%20Hudayyah&format=json&limit=1,YE,YE
3,1691,pacs.008,ES,"Calle Bosc, Cataluña, Rubí , , 8191",",",Calle Bosc,Cataluña,Rubí,,,8191,ES,"catalonia is not a city, but a region, and Rubi is a city in the region.",ES,ES
4,736,pacs.008,IL,"Nitsanim Haifa Haifa , , 34354 37",: 34354,Nitsanim,Haifa,Haifa,,,34354,IL,: 0.2,IL,IL

# Recall, Precision and Accuracy Rates

True Positives = Wires which the deciphered countries matched with the verified countries <br>
False Positives = Wires which the deciphered countries do not matched with the verified countries <br>
False Negatives = Wires which the deciphered countries are "Unknown".

In [175]:
TP = (df1['CountryCodeVerified'] == df1['CountryCodeFinal']).sum()
FP = (df1['CountryCodeVerified'] != df1['CountryCodeFinal']).sum()
FN = (df1['CountryCodeFinal']=="Unknown").sum()

<b><font size=3>Recall Rate</font></b>

In [176]:
TP/(TP+FN)

np.float64(1.0)

<b><font size=3>Precision Rate</font></b>

In [177]:
TP/(TP+FP)

np.float64(0.805)

<b><font size=3>Acccracy Rate</font></b>

In [178]:
TP/df1.shape[0]

np.float64(0.805)

In [179]:
# Exporting the final result to an Excel file.
df1.to_excel("gdrive/MyDrive/Github_Projects/LLM_Address_Deciphered_Result.xlsx", index=False)